### ISSUE TITLE
GUI Crash

### ISSUE THREAD

**Issue by ghost** [LittleBreadLoaf/Fantastic-Fish#1] opened 2015-03-02 16:29 UTC
Something in the mod is causing a minecraft:glass_pane shapeless recipe to trigger a crash when a single glass pane is placed into a crafting table/ inventory-crafting.
NEI is showing the recipe is trying to turn the glass into a minecraft:fire item.
I performed a mod-by-mod test to try and find where the culprit appeared and unfortunately, it landed on FantasticFish1.4

I've had to patch it up by forcing the recipe to be nulled with CraftingManager as a temporary solution.

Note; Smashing mod, can't believe how well it performs.

**Comment by Frag2000** [comment] 2015-03-02 19:47
Actually, I was able to reproduce. And yes, this is caused by fantastic fish. I removed the mod and everything started to work fine again.
I am taking note of this and will fix it before the release.
Thanks Draylynn!

**Comment by Frag2000** [comment] 2015-03-04 03:25
This was fixed in the next release. Alpha 1.5

**Closed as completed by Frag2000** 2015-03-04 03:25 UTC
